### Настройки DevSecOps ###
### Общая информация о команде ###
team:
  - {
      # код ЕАСУП команды в справочнике SberWorks (доступен только в домене Sigma)
      mus_code: "00160065",
      # название команды в справочнике SberWorks (доступен только в домене Sigma)
      mus_name: "Структурирование сделки. CRM продукты КБ",
      # почтовый адрес Product Owner для уведомлений с результатами сканирования. Возможно указание нескольких email через ;
      mus_po_mail: "Ulybin.A.Al@sberbank.ru;Menshikov.A.Serge@sberbank.ru",
    }
#  - {
#      # Вторую и последующие команды необходимо добавить по формату, аналогично первой
#      mus_code: "00040018",
#      # название команды в справочнике SberWorks
#      mus_name: "Web SBOL Design",
#      # почтовый адрес Product Owner для уведомлений с результатами сканирования. Возможно указание нескольких email через ;
#      mus_po_mail: "sspetrov@sberbank.ru",
#    }

### Общая информация о приложении ###
app:
  # конфигурационный элемент КЭ приложения / модуля ПО в Service Manager (необходимо проверить наличие в справочнике АС, доступен только в домене Sigma)
  sm_id: "CI02926644"
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: "ППРБ.КФЮЛ.Условия кредитования"
### Настройки SAST Checkmarx ###
sast_cx:
  # сredentials id в Jenkins для учетной записи Checkmarx одной команды, под которой будет проводиться сканирование (настраивались на шаге 1.4)
  creds_id: "sast_creds"
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: "CRDTRM"
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана. Пример: "!**/utils/**/*.xml" - исключение всех xml файлов в папке utils
  masks: "!**/node_modules/**/*"
  # id профиля сканирования, по умолчанию 36. 14 - для мобильного приложения. 100003 - Smoke
  preset_id: "36"
  # макс время ожидания статуса QG в минутах
  wait_qg: "2"
  ###
